// Shared restaurant directory for the UTC dining tracker and tier list.
// status: 'open' (default) | 'soon' | 'closed'
const RESTAURANTS = [
  { name: "85°C Bakery Café", category: "Bakery & Sweets" },
  { name: "Batch & Box", category: "Bakery & Sweets" },
  { name: "Bazille", category: "American" },
  { name: "BenGong's Tea", category: "Coffee & Tea" },
  { name: "Blue Bottle Coffee", category: "Coffee & Tea" },
  { name: "Blue Ocean Sushi & Grill", category: "Asian" },
  { name: "Board & Brew Specialty Sandwiches", category: "Quick Bites" },
  { name: "Capital One Café", category: "Coffee & Tea" },
  { name: "CHAGEE Modern Teahouse", category: "Coffee & Tea", status: "soon" },
  { name: "Charleys", category: "Quick Bites" },
  { name: "Corner Bakery", category: "Bakery & Sweets" },
  { name: "Crepe Delicious", category: "Bakery & Sweets" },
  { name: "Din Tai Fung", category: "Asian" },
  { name: "Eureka! Discover American Craft", category: "American" },
  { name: "Gen Korean BBQ", category: "Asian" },
  { name: "Hai Di Lao", category: "Asian" },
  { name: "Hanna's Creamery & Cafe", category: "Ice Cream & Frozen" },
  { name: "Happy Lemon", category: "Coffee & Tea" },
  { name: "HeyTea", category: "Coffee & Tea" },
  { name: "Javier's", category: "Mexican & Latin" },
  { name: "Joe & The Juice", category: "Healthy & Juice" },
  { name: "JOEY La Jolla", category: "American" },
  { name: "Katsuya KO", category: "Asian" },
  { name: "La Colombe", category: "Coffee & Tea" },
  { name: "Laderach", category: "Bakery & Sweets" },
  { name: "Lady M Cake Boutique", category: "Bakery & Sweets" },
  { name: "Le Macaron", category: "Bakery & Sweets" },
  { name: "Lucrezia", category: "Italian" },
  { name: "Marugame Udon", category: "Asian" },
  { name: "Melo Melo", category: "Bakery & Sweets" },
  { name: "Menya Ultra", category: "Asian" },
  { name: "Nespresso", category: "Coffee & Tea", status: "closed" },
  { name: "Nespresso Pop-Up", category: "Coffee & Tea" },
  { name: "Nice Rice", category: "Asian" },
  { name: "Nordstrom E-Bar", category: "Coffee & Tea" },
  { name: "Onigilly Japanese Kitchen", category: "Asian", status: "soon" },
  { name: "Pacific Catch", category: "American" },
  { name: "Panda Express", category: "Asian" },
  { name: "Panini Kabob Grill", category: "Mediterranean" },
  { name: "Parana Empanadas", category: "Mexican & Latin" },
  { name: "Parfait Paris", category: "Bakery & Sweets" },
  { name: "Pazza Market and Cucina", category: "Italian" },
  { name: "Pinkberry", category: "Ice Cream & Frozen" },
  { name: "Qin West Noodle", category: "Asian" },
  { name: "Queenstown Bistro", category: "American" },
  { name: "Raised by Wolves", category: "American" },
  { name: "Ramen Nagi", category: "Asian" },
  { name: "Rising Sun Sushi", category: "Asian" },
  { name: "Royal India", category: "Asian" },
  { name: "Salt & Straw", category: "Ice Cream & Frozen" },
  { name: "Sbarro", category: "Italian" },
  { name: "Seasons 52", category: "American" },
  { name: "See's Candies", category: "Bakery & Sweets" },
  { name: "Shake Shack", category: "American" },
  { name: "Silverlake Ramen", category: "Asian" },
  { name: "Sip Fresh", category: "Healthy & Juice" },
  { name: "Slurp", category: "Asian" },
  { name: "Smashburger", category: "American" },
  { name: "SomiSomi", category: "Ice Cream & Frozen" },
  { name: "Starbucks", category: "Coffee & Tea", status: "closed" },
  { name: "Suki Hana", category: "Asian" },
  { name: "Superberry Açaí", category: "Healthy & Juice" },
  { name: "Swagyu Burger", category: "American" },
  { name: "Sweetgreen", category: "Healthy & Juice" },
  { name: "Teleferic Barcelona", category: "Mediterranean", status: "soon" },
  { name: "Tender Greens", category: "Healthy & Juice" },
  { name: "The Amalfi Llama", category: "Italian" },
  { name: "True Food Kitchen", category: "Healthy & Juice" },
  { name: "Van Leeuwen Ice Cream", category: "Ice Cream & Frozen" },
  { name: "Venchi", category: "Ice Cream & Frozen" },
  { name: "Wetzel's Pretzels", category: "Quick Bites" },
  { name: "Wushiland Boba", category: "Coffee & Tea" },
];
